name: Build, Test and Publish ABCpdf Images

on:
  push:
    branches:
      - Add-26.04-and-simplify-tests
  schedule:
     - cron: '0 3 * * 2'  # 4am UK time on Tuesdays (3am UTC for BST, 4am UTC would be 5am BST)
  workflow_dispatch:

jobs:
  build-test-publish-base-images:
    runs-on: ubuntu-latest
    strategy:
      #fail-fast: false # Continue running all jobs in the matrix even if one fails
      matrix:
        include:
          - os: "bookworm-slim"
            dotnet-version: "8.0"
            abcpdf-version: "13"
            abcchrome-version: "123"

          - os: "22.04-jammy"
            dotnet-version: "8.0"
            abcpdf-version: "13"
            abcchrome-version: "123"

          - os: "24.04-noble"
            dotnet-version: "8.0"
            abcpdf-version: "13"
            abcchrome-version: "123"

          # - os: "26.04-resolute"
          #   dotnet-version: "10.0"
          #   abcpdf-version: "14"
          #   abcchrome-version: "123"

          # - os: "26.04-resolute"
          #   dotnet-version: "10.0"
          #   abcpdf-version: "14"
          #   abcchrome-version: "146"
    env:
      DOTNET_VERSION: ${{ matrix.dotnet-version }}
      BASE_IMAGE_TAG: abcpdf/mcr-aspnet:${{ matrix.dotnet-version }}-${{ matrix.os }}-${{ github.sha }}
      TEST_APP_IMAGE_TAG: abcpdf_test_app_container:${{ matrix.dotnet-version }}-${{ matrix.os }}
      PUBLISH_IMAGE_TAG: abcpdf/mcr-aspnet:${{ matrix.dotnet-version }}-${{ matrix.os }}
    steps:
    - uses: actions/checkout@v6
    - name: Build and test base Image and application image
      run: |
        chmod +x ./build-and-test-distro.sh
        ./build-and-test-distro.sh ${{ matrix.os }} ${{ matrix.dotnet-version }} ${{ matrix.abcpdf-version }} ${{ matrix.abcchrome-version }} ${{ secrets.ABCPDF14_LICENSE_KEY }}
